### ISSUE TITLE
Question about generating audio (longer than 10s)

### ISSUE THREAD

**Issue by albertwy** [v-iashin/SpecVQGAN#23]
Hi, thanks for your sharing!  I want use the pre-trained model to generate audio longer than 10s, but i don't know how to achieve it? could you please give me some suggestions? Thanks a lots!

**Comment by v-iashin** [comment]
In google colab, it is 

W_scale (int > 0): the output sound duration will be W_scale * 9.8 seconds

In the streamlit demo, it is

“temporal scale”

**Comment by fengping1** [comment]
Hi, thanks for  sharing! i want to train a codebook which can generate much longer sound, do you have any clue?

**Comment by v-iashin** [comment]
Hi, the current codebook supports arbitrary length input. You can already generate audio of any length

**Comment by Tri-Ergon** [comment]
May I ask if my video is 45 second, can the model directly generate 45 seconds audio, or do I need to first generate audio with 9.8*5=49s, then trim the audio to 45s?

**Comment by BingliangLi** [comment]
May I ask if my video is 45 second, can the model directly generate 45 seconds audio, or do I need to first generate audio with 9.8*5=49s, then trim the audio to 45s?
