### ISSUE TITLE
Issues with training transformer on the VAS dataset

### ISSUE THREAD

**Issue by mayqinxu** [v-iashin/SpecVQGAN#25]
Hi Vladimir, thanks for the great project / repo!

I'm having issues with using the train.py to train the transformer on the VAS dataset (Resnet50 1Feat). Every time I train, the process stops at the 5th epoch. It seems to have triggered early stopping. Is this normal or I should check my config file?

**Comment by v-iashin** [comment]
Hi, as far as I remember, it is ok. Transformer training should be much faster than autoencoder training. To confirm this, inspect your validation loss which should start getting into “u” shape

**Comment by mayqinxu** [comment]
> Hi, as far as I remember, it is ok. Transformer training should be much faster than autoencoder training. To confirm this, inspect your validation loss which should start getting into “u” shape

Thanks a lot!

**Comment by v-iashin** [comment]
You may also look in Section 6.1.4 second paragraph for details (https://arxiv.org/pdf/2110.08791.pdf).
