### ISSUE TITLE
netG.pt, optG.pt, netD.pt, optD.pt files of the MelGAN model

### ISSUE THREAD

**Issue by xuihan** [v-iashin/SpecVQGAN#27]
hello,
I want to fine-tune on your pre-trained VGGSound_MelGAN model.
if possible, can I have the honor to get your netG.pt(you have provided), optG.pt, netD.pt, optD.pt files?

**Comment by v-iashin** [comment]
Hi, thanks.

Actually, I do have them. Updated the README: 
https://github.com/v-iashin/SpecVQGAN/commit/8ab6981535ab70fad3531688e0f630f1ce3b834f

**Comment by v-iashin** [comment]
Just in case,
```
e61cd6da221d1d3b423c70c20660361c  logs/vggsound/netD.pt
e9e3ea89122d31e3dec25f585d215335  logs/vggsound/netG.pt
50804e7d0c9453a29f374dba73787680  logs/vggsound/optD.pt
85ed142485ba81bb3c5727ae0b3fbb84  logs/vggsound/optG.pt
```

**Comment by xuihan** [comment]
> Hi, thanks.
> 
> Actually, I do have them. Updated the README: [8ab6981](https://github.com/v-iashin/SpecVQGAN/commit/8ab6981535ab70fad3531688e0f630f1ce3b834f)

Thank you so so so so so  much for your prompt reply!
