### ISSUE TITLE
Number of different features 

### ISSUE THREAD

**Issue by xuihan** [v-iashin/SpecVQGAN#31]
Hello,
By reading your paper, I know how 212 feats are obtained. But it is not clear about 1 feat and 5 feats.
May I ask how the 1 feat and 5 feats of the resnet50 model mentioned in your paper were obtained?

![ca4faf39780c9240543701c59c14e80](https://user-images.githubusercontent.com/79632373/236406920-b1fdf783-63c7-41af-9cf3-fbbf686fa464.png)

**Comment by v-iashin** [comment]
here you go

https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/specvqgan/data/vggsound.py#L55-L76

**Comment by xuihan** [comment]
> here you go
> 
> https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/specvqgan/data/vggsound.py#L55-L76

Thank you very much for your serious answer every time!
