### ISSUE TITLE
Seeking Advice on MelGAN Model Training

### ISSUE THREAD

**Issue by Ivvvvvvvvvvy** [v-iashin/SpecVQGAN#36]
Hello, I would like to ask about your experience in training the MelGAN model. I have trained it using my own dataset containing 10,000 audio samples. I trained the model for 1200 epochs, which took approximately 350k iterations and around 24 hours to complete. However, the results are not very satisfactory. The generated voices and bird sounds are of poor quality, and they are unrecognizable as human voices or bird calls.
![31137eb30c33b3040133d9367c65455](https://github.com/v-iashin/SpecVQGAN/assets/79632373/c9635c6f-657a-43ae-919c-b27efbbd85b9)

I used the default parameters, except for changing the batch size to 32. Here are the detailed information.
What parameters do I need to adjust to generate better audio? Will reducing the batch size to 16 and lengthening the training time help?
Very much looking forward to your guidance！！！！

```!!python/object:argparse.Namespace
batch_size: 32
cond_disc: false
data_path: !!python/object/apply:pathlib.PosixPath
- /
- root
- autodl-tmp
- SpecVQGAN
- data
- soundscape
- feature
- mel_audio
downsamp_factor: 4
epochs: 100000
lambda_feat: 10
load_path: null
log_interval: 100
n_layers_D: 4
n_mel_channels: 80
n_residual_layers: 3
n_test_samples: 8
ndf: 16
ngf: 32
num_D: 3
save_interval: 1000
save_path: ./logs/soundscape/2023-11-17T20-14-41
seq_len: 8192
splits_path: !!python/object/apply:pathlib.PosixPath
- data
```

**Comment by v-iashin** [comment]
as far as i remember, it took some time to train it. try to keep on training it for another 6 days and see how it goes.

**Comment by Ivvvvvvvvvvy** [comment]
Hello, I want to confirm something for you! ! ! I have two forms of audio features, files with "_mel" suffix and files with "_audio" suffix. 
![97603d30961671cd4cd48b39f06d757](https://github.com/v-iashin/SpecVQGAN/assets/79632373/6c7e105c-c19f-45bc-b986-c45fd418a703)
![0bf94a09c5f6af55ccb7effcee95465](https://github.com/v-iashin/SpecVQGAN/assets/79632373/6e17936d-54ac-48a5-a7ec-d38b68db0588)


The data I input when training the melgan model was a mel spectrogram file with the "_mel" suffix, but an error occurred during training. The information is as follows.
```
 File "scripts/train.py", line 233, in <module>
    main()
  File "scripts/train.py", line 106, in main
    for i, x_t in enumerate(test_loader):
  File "/root/miniconda3/envs/specvqgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/specvqgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/specvqgan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/specvqgan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./mel2wav/dataset.py", line 42, in __getitem__
    audio, sampling_rate = self.load_wav_to_torch(filename)
  File "./mel2wav/dataset.py", line 63, in load_wav_to_torch
    data = np.load(full_path)
  File "/root/miniconda3/envs/specvqgan/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/SpecVQGAN/data/soundscape/feature/melspec_10s_22050hz/4023_audio.npy'
```
So I changed to input the _audio file, and the training went on normally, but I see that you are using the mel spectrogram file with the suffix "_mel". I am not sure if my operation is correct!!
Please give me some advice! !
