### ISSUE TITLE
Spectrogram VQGAN as a Neural Audio Codec

### ISSUE THREAD

**Issue by a897456** [v-iashin/SpecVQGAN#38]
># Spectrogram VQGAN as a Neural Audio Codec
>model_name = '2021-05-19T22-16-54_vggsound_codebook'
>log_dir = './logs'
>config, model, vocoder = load_neural_audio_codec(model_name, log_dir, device)

# I tried to experiment with this part of the function: 'Spectrogram VQGAN as a Neural Audio Codec', when I downloaded the pre-trained model, the code did not run and the following error appeared. 

E:\ProgramData\anaconda3\envs\py39\python.exe C:\Users\User1\Desktop\SpecVQGAN-main\specVQ.py 
Using: 2021-05-19T22-16-54_vggsound_codebook (VGGSound Codebook)
881MB [01:25, 10.3MB/s]                           
Unpacking ./logs\2021-05-19T22-16-54_vggsound_codebook.tar.gz to ./logs
./logs/2021-05-19T22-16-54_vggsound_codebook/checkpoints/last.ckpt
Traceback (most recent call last):
  File "C:\Users\User1\Desktop\SpecVQGAN-main\specVQ.py", line 19, in <module>
    config, model, vocoder = load_neural_audio_codec(model_name, log_dir, device)
  File "C:\Users\User1\Desktop\SpecVQGAN-main\feature_extraction\demo_utils.py", line 211, in load_neural_audio_codec
    model = instantiate_from_config(config.model)
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\train.py", line 131, in instantiate_from_config
    return get_obj_from_str(config['target'])(**config.get('params', dict()))
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\specvqgan\models\vqgan.py", line 31, in __init__
    self.loss = instantiate_from_config(lossconfig)
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\train.py", line 131, in instantiate_from_config
    return get_obj_from_str(config['target'])(**config.get('params', dict()))
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\specvqgan\modules\losses\vqperceptual.py", line 47, in __init__
    self.perceptual_loss = LPAPS().eval()
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\specvqgan\modules\losses\lpaps.py", line 23, in __init__
    self.net = vggishish16(pretrained=True, requires_grad=False)
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\specvqgan\modules\losses\lpaps.py", line 91, in __init__
    vgg_pretrained_features = self.vggishish16(pretrained=pretrained).features
  File "C:\Users\User1\Desktop\SpecVQGAN-main\.\specvqgan\modules\losses\lpaps.py", line 134, in vggishish16
    ckpt = torch.load(ckpt_path, map_location=torch.device("cpu"))
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by v-iashin** [comment]
hi, thanks for trying it out.

based on the error message you are getting, I think, the weights file is corrupted. try removing it and repeating the steps

https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory

**Comment by v-iashin** [comment]
```
File "C:\Users\User1\Desktop\SpecVQGAN-main.\specvqgan\modules\losses\lpaps.py", line 134, in vggishish16
ckpt = torch.load(ckpt_path, map_location=torch.device("cpu"))
```
to narrow it down even more, check the vggishish weights.

**Comment by a897456** [comment]
> File "C:\Users\User1\Desktop\SpecVQGAN-main.\specvqgan\modules\losses\lpaps.py", line 134, in vggishish16
> ckpt = torch.load(ckpt_path, map_location=torch.device("cpu"))
> 
> to narrow it down even more, check the vggishish weights.

![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/fb8c6f44-f68f-4066-bba7-942b0a39809f)
Is the ".pt" file too small? Is it not fully downloaded? Is that the reason?

**Comment by a897456** [comment]
>#Spectrogram Extraction
>model_sr = config.data.params.sample_rate
># duration = get_duration(input_wav)
>spec = extract_melspectrogram(input_wav, sr=model_sr, duration=duration)
>print(f'Audio Duration: {duration} seconds')
>print('Original Spectrogram Shape:', spec.shape)

# Thank you for your quick reply, but I have a second question. The code in bold has the following error.

E:\ProgramData\anaconda3\envs\py39\python.exe C:\Users\User1\Desktop\SpecVQGAN-main\specVQ.py 
Using: 2021-05-19T22-16-54_vggsound_codebook (VGGSound Codebook)
./logs/2021-05-19T22-16-54_vggsound_codebook/checkpoints/last.ckpt
loaded pretrained LPAPS loss from specvqgan/modules/autoencoder/lpaps\vggishish16.pt
VQLPAPSWithDiscriminator running with hinge loss.
Restored from ./logs/2021-05-19T22-16-54_vggsound_codebook/checkpoints/last.ckpt
Traceback (most recent call last):
  File "C:\Users\User1\Desktop\SpecVQGAN-main\specVQ.py", line 32, in <module>
    duration = get_duration(input_wav)
  File "C:\Users\User1\Desktop\SpecVQGAN-main\feature_extraction\demo_utils.py", line 67, in get_duration
    result = subprocess.run(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "E:\ProgramData\anaconda3\envs\py39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\ProgramData\anaconda3\envs\py39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\ProgramData\anaconda3\envs\py39\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by v-iashin** [comment]
```
result = subprocess.run(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```
just debug this line. most likely `ffmpeg` is not installed or whatever you're feeding to it does not exist (`-i X`) or the output path's folder does not exist.

**Comment by a897456** [comment]
> ```
> result = subprocess.run(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> ```
> 
> just debug this line. most likely `ffmpeg` is not installed or whatever you're feeding to it does not exist (`-i X`) or the output path's folder does not exist.

# I just installed ‘ffmpeg’ and also created the output path's folder: “./tmp/neural_audio_codec”. And then debug the line you mentioned and it shows the result as shown below:
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/f909daae-bcb6-4781-95b3-c0de232df91d)
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/188e66b7-7fc7-4031-a6e9-200deb5b9caf)

**Comment by a897456** [comment]
# add 
E:\ProgramData\anaconda3\envs\py39\python.exe "E:/Program Files/JetBrains/PyCharm 2023.2.4/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 53021 --file C:\Users\User1\Desktop\SpecVQGAN-main\specVQ.py 
已连接到 pydev 调试器(内部版本号 232.10203.26)Using: 2021-05-19T22-16-54_vggsound_codebook (VGGSound Codebook)
./logs/2021-05-19T22-16-54_vggsound_codebook/checkpoints/last.ckpt
loaded pretrained LPAPS loss from specvqgan/modules/autoencoder/lpaps\vggishish16.pt
VQLPAPSWithDiscriminator running with hinge loss.
Restored from ./logs/2021-05-19T22-16-54_vggsound_codebook/checkpoints/last.ckpt
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\py39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\ProgramData\anaconda3\envs\py39\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  File "E:\Program Files\JetBrains\PyCharm 2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 585, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, patch_arg_str_win(cmd_line), *args)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
python-BaseException

**Comment by v-iashin** [comment]
it complains that `ffprobe` is missing. this means that `ffmpeg`/`ffprobe` is not in your `PATH`.

**Comment by a897456** [comment]
> it complains that `ffprobe` is missing. this means that `ffmpeg`/`ffprobe` is not in your `PATH`.

You are the fastest replying blogger I have ever met in github web, thanks for your quick reply.
I am sorry, I'm a newbie and I don't understand what 'my path' means.

**Comment by v-iashin** [comment]
`PATH` is a variable in your system that specifies the directories to be searched to find a command (`ffprobe`, `ffmpeg`, `python`, `pip` etc). 

most likely, you just forgot to activate your conda environment (that has ffmpeg installed). Python does not see your ffmpeg installation

**Comment by a897456** [comment]
# you mean the virtual environment? like this:
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/543bbbfb-9f93-421e-87b8-dbcde2aa385a)
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/07d8ebbf-7753-447f-8611-0d75b09617dc)

**Comment by v-iashin** [comment]
activate your `py38` environment and type
```bash
which ffmpeg
which ffprobe
```
both should return paths to libraries. if so, try running your python script from this environment.

**Comment by a897456** [comment]
> activate your `py38` environment and type
> 
> ```shell
> which ffmpeg
> which ffprobe
> ```
> 
> both should return paths to libraries. if so, try running your python script from this environment.

# Do you mean that the py39 version I am using now is too high? I need to change to py38 version, right?
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/9d5a9981-2fdb-4ff0-882e-10dd646d7608)

**Comment by v-iashin** [comment]
sorry, i meant `py39`

**Comment by a897456** [comment]
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/b56e7de7-3b92-406a-bbe2-f3710138a447)

**Comment by a897456** [comment]
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/cb68ea0d-3afb-4208-823e-fec4afa242d7)

**Comment by a897456** [comment]
I modified part of the code, the code ran but the output sound is very bad, you can try to listen to it: https://drive.google.com/drive/folders/1fs5GrArIuFdUaufaUAXaT4UHEyd2ja6b?usp=drive_link

I modified part of the code, as follows: 
1. "input_wav" be changed by "input_npy" which comes from HIFIGAN
2. "sepc=extract_melspectrogram(...)" be changed by "spec = np.load(input_npy)"
3. "duration = get_duration(...)" be changed by "duration=3"
![image](https://github.com/v-iashin/SpecVQGAN/assets/28752526/620abb57-caa1-4873-aa02-dd1bc278820e)

**Comment by v-iashin** [comment]
your samples are private.

we are using melgan, not hifigan.

try it on google colab. the code works in that environment
https://colab.research.google.com/drive/1K_-e6CRQFLk9Uq6O46FOsAYt63TeEdXf?usp=sharing

**Comment by v-iashin** [comment]
[reference_sample.zip](https://github.com/v-iashin/SpecVQGAN/files/14406451/reference_sample.zip)

i added your audio to google colab and this is what I got. please fix your local environment. the code should work.

if you have windows, consider wsl or docker. i am afraid, windows support is out of scope of this repository.

good luck in learning!

**Comment by a897456** [comment]
> [reference_sample.zip](https://github.com/v-iashin/SpecVQGAN/files/14406451/reference_sample.zip)
> 
Sorry for replying you so late. The last time I replied to you yesterday was already 11pm
These files in zip can't be played. Is that okay on your side?

**Comment by a897456** [comment]
[https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/feature_extraction/demo_utils.py#L373]
kbps and bps should have been 1000 times, not 1024, right?

**Comment by v-iashin** [comment]
Yes, it is ok on my side. 

Yes, it is a mistake. It should be 1000.

**Comment by a897456** [comment]
https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/feature_extraction/demo_utils.py#L215

If I want to change the vocoder, and then I download other checkpoint, such as hifigan.pt, and then put it in the ". / vocoder/logs/vggsound/hifigan.pt ", right? 
But it didn't work, so I was wondering if this vocoder (MelGAN) was trained with both of your models? The vocoder cannot be replaced directly.

**Comment by a897456** [comment]
https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/feature_extraction/demo_utils.py#L373
embedding=1024x256

**Comment by a897456** [comment]
https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/feature_extraction/demo_utils.py#L372
codebook_size=model.quantize.e_dim or model.quantize.n_e?

**Comment by a897456** [comment]
> https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/feature_extraction/demo_utils.py#L373
> 
> kbps and bps should have been 1000 times, not 1024, right?

wav → spec[80,832] →  [1,1,80,832] →  [1,256,5,52]
The whole process only uses a 1024x256 codebook, so bit=10x8/duration, right?
