### ISSUE TITLE
How is the diffusion model represented in this chapter?

### ISSUE THREAD

**Issue by a897456** [v-iashin/SpecVQGAN#40]
https://github.com/v-iashin/SpecVQGAN/blob/main/specvqgan/modules/diffusionmodules/model.py

**Comment by v-iashin** [comment]
This module wasn’t used.

**Comment by a897456** [comment]
> This module wasn’t used.

Did you have a project on speech bit rate processing with diffusion model?

**Comment by v-iashin** [comment]
No, I didn't

**Comment by a897456** [comment]
> This module wasn’t used.

Is the code in the module of the diffusionmodules also incomplete?

**Comment by v-iashin** [comment]
most likely not. this bit was inherited from https://github.com/CompVis/taming-transformers
