### ISSUE TITLE
evaluate issue

### ISSUE THREAD

**Issue by JokerHYX-719** [v-iashin/SpecVQGAN#46]
In the process of sampling, I encountered the issue "bash: sampler.splits[validation, ]: command not found."The parameters I used are as follows:
python evaluation/generate_samples.py \
        sampler.config_sampler=evaluation/configs/sampler.yaml \
        sampler.model_logdir="./logs/2024-08-30T17-40-59_vas_transformer"
        sampler.splits"[validation, ]" \ 
        sampler.samples_per_video=10 \
        sampler.batch_size=4 \
        sampler.top_k=64 \
        data.params.spec_dir_path="./data/vas/features/*/melspec_10s_22050hz/" \
        data.params.rgb_feats_dir_path="./data/vas/features/*/feature_rgb_bninception_dim1024_21.5fps/" \
        data.params.flow_feats_dir_path="./data/vas/features/*/feature_flow_bninception_dim1024_21.5fps/" \

**Comment by JokerHYX-719** [comment]
How can I resolve this issue

**Comment by v-iashin** [comment]
try adding `\` at the end of each line except for the last one

**Comment by JokerHYX-719** [comment]
Thank you very much!

**Comment by JokerHYX-719** [comment]
May I ask why I set sampler.samples_per_video=10 but the training shows 1

**Comment by JokerHYX-719** [comment]
![image](https://github.com/user-attachments/assets/3575e3a7-1212-41c2-9366-06819722fbc0)

**Comment by v-iashin** [comment]
read `6.1.7 Evaluation of Generated Samples` for details
